version: 1.0.{build}
image: Visual Studio 2019
configuration:
  - Release
environment:
  matrix:
  - job_name: Build
  
  - job_name: Tests A
    job_group: Tests
    job_depends_on: Build
    
  - job_name: Tests B
    job_group: Tests
    job_depends_on: Build
  
  - job_name: Tests C
    job_group: Tests
    job_depends_on: Build
    
cache:
  - packages -> **\packages.config
nuget:
  project_feed: true
before_build:
  - nuget config -set repositoryPath=C:\projects\example-csharp-master-p0csp\packages -configfile C:\projects\example-csharp-master-p0csp\nuget.config
  - nuget restore 
  - choco install opencover.portable
  - choco install codecov
build:
  project: CodecovProject.sln
  verbosity: detailed
test_script:
  - ps: write-host "Common Tests"
matrix:
  fast_finish: true

for:
  -
    matrix:
      only:
        - configuration: Release
          job_name: Tests A
    environment:
      my_var1: overriden-value1
    platform: Any CPU # this setting is ignored
    test_script:
      - ps: write-host "for-matrix override test script 1"

  -
    matrix:
      only:
        - configuration: Release
          job_name: Tests B
    environment:
      my_var1: overriden-value1
    platform: Any CPU # this setting is ignored
    test_script:
      - ps: write-host "for-matrix override test script 2"