version: 1.0.{build}
image: Visual Studio 2019
platform: Any CPU
environment:
  matrix:
  - job_name: Build
  
  - job_name: Tests A
    job_group: Tests
    job_depends_on: Build
    
  - job_name: Tests B
    job_group: Tests
    job_depends_on: Build
  
  - job_name: Tests C
    job_group: Tests
    job_depends_on: Build
    
cache:
  - packages -> **\packages.config
nuget:
  project_feed: true
before_build:
  - nuget config -set repositoryPath=C:\projects\example-csharp-master\packages -configfile C:\projects\example-csharp-master\nuget.config
  - nuget restore 
  - choco install opencover.portable
  - choco install codecov
build:
  project: CodecovProject.sln
  verbosity: detailed
  
for:
  -
   matrix:
      only:
      job_name: Tests A
    test_script:
      - ps: write-host "for-matrix override test script A"
    
  -
    matrix:
      only:
      job_name: Tests B
    test_script:
      - ps: write-host "for-matrix override test script B"
   
  -
    matrix:
      only:
      job_name: Tests C
    test_script:
      - ps: write-host "for-matrix override test script C"