version: 1.0.{build}
image: Visual Studio 2019
platform: Any CPU
cache:
  - packages -> **\packages.config
nuget:
  project_feed: true
before_build:
  - nuget config -set repositoryPath=C:\projects\example-csharp-master\packages -configfile C:\projects\example-csharp-master\nuget.config
  - nuget restore 
  - choco install opencover.portable
  - choco install codecov
build:
  project: CodecovProject.sln
  verbosity: detailed

after_build:
  - ls -r > out.txt
  - findstr "MyUnitTests" out.txt  
  
test_script:
  - OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" -targetargs:"MyUnitTests\bin\Debug\MyUnitTests.dll" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:"MyProject_coverage.xml"
  - codecov -f "MyProject_coverage.xml"  -t beb94cc5-4595-4b5b-ab4f-93e8ea073b6d