version: 1.0.{build}
image: Visual Studio 2019
platform: Any CPU
nuget:
  account_feed: true
before_build:
  - dotnet restore
  - nuget restore CodecovProject.sln
  - choco install opencover.portable
  - choco install codecov

build:
  project: CodecovProject.sln
  verbosity: detailed
 
test_script:
- OpenCover.Console.exe -register:user -target:"C:\Program Files (x86)\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" -targetargs:"MyUnitTests\bin\Debug\MyUnitTests.dll" -filter:"+[UnitTestTargetProject*]* -[MyUnitTests*]*" -output:".\MyProject_coverage.xml"
- codecov -f "MyProject_coverage.xml"  -t beb94cc5-4595-4b5b-ab4f-93e8ea073b6d
  dir /s
